name: naturalista
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  mocktail: ^1.0.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  skeletonizer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
